# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

r_binary_packages:
  - devtools
  - roxygen2

script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz

#after_success:
#  - Rscript -e "devtools::install();devtools::test()"
